### ISSUE TITLE
About Menu

### ISSUE THREAD

**Issue by sebgie** [TryGhost/Ghost-Desktop#107]
OCD: The `About` menu shows a version number that doesn't make any sense? I guess it's the electron version? Would it be possible to show the Ghost-Desktop version as well?

**Comment by felixrieseberg** [comment]
Yep, good catch.

**Comment by felixrieseberg** [comment]
Closed upstream in https://github.com/felixrieseberg/ember-electron/commit/e7b576fdeda9885f8aef10fa40df366d518b6901.
