### ISSUE TITLE
Focus lost in compose screen while switching applications

### ISSUE THREAD

**Issue by jaredharley** [TryGhost/Ghost-Desktop#116]
I am running Ghost-Desktop Version 0.3.1 (0.3.1) on OS X El Capitan 10.11.4.

I have found that, as I am authoring a new post, if I switch applications (using cmd+tab) to check something and switch back, the keyboard input focus has been lost in the editor area. I then have to click inside the editor again to continue typing.

The web editor hosted on my server does not have this problem - I can switch to other browser tabs and applications, and my input cursor stays active so I can quickly begin typing again.

**Comment by felixrieseberg** [comment]
I can see how that is super annoying - we'll definitely fix that.

**Comment by jaredharley** [comment]
Awesome, thanks! Just checked, and the issue exists in Version 0.3.2 as well.
