### ISSUE TITLE
Support for font-size on Linux Hi-DPI.

### ISSUE THREAD

**Issue by envygeeks** [TryGhost/Ghost-Desktop#122]
On Linux Hi-DPI screens, unless we jump above 1.3x Chrome apps will not scale for us.  While even though most do not consider 1980 on a laptop hi-dpi technically it is so it scales and Chrome does not recognize this on Linux.  Can we please get a default font-size setting?

**Comment by felixrieseberg** [comment]
Sounds good to me 👍 .
