### ISSUE TITLE
Missing maintainer in ubuntu debian file

### ISSUE THREAD

**Issue by krnekhelesh** [TryGhost/Ghost-Desktop#124]
It is mandatory for the debian control file to have a maintainer [[1]](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Maintainer). Otherwise, all ubuntu users see the following warning message any time they update their system,

dpkg: warning: parsing file '/var/lib/dpkg/status' near line 11018 package 'ghost':
 missing maintainer
Setting up language-selector-common (0.165.1) ...
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 11018 package 'ghost':
 missing maintainer
Setting up language-selector-gnome (0.165.1) ...
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 11018 package 'ghost':
 missing maintainer
Setting up python3-distupgrade (1:16.04.14) ...
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 11018 package 'ghost':
 missing maintainer
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 11014 package 'ghost':
 missing maintainer

**Comment by felixrieseberg** [comment]
Thank you very much - I'm basically a noob when it comes to Ubuntu packages, so that helps a lot.
