### ISSUE TITLE
When loading blog I just get stuck on the loading screen

### ISSUE THREAD

**Issue by boardy** [TryGhost/Ghost-Desktop#125]
After entering my details, the window just shows the in progress circle and doesn't change. I've left for around 10 minutes but nothing from the blog is displayed.

**Comment by ErisDS** [comment]
Not 100% sure but my first guess here would be that your blog is running an old & incompatible version of Ghost. Could that be a possibility? It would be super helpful if you could provide a few details about your blog, like the version, where it runs, which DB it uses and any special config that you have.

**Comment by boardy** [comment]
Oops I should have checked that, it was an older version which I've upgraded now and thedesktop app works fine. Apologies.

It may be helpful for others who haven't realised if it could display an error though instead of just staying stuck loading.

**Comment by felixrieseberg** [comment]
Totally right, we should have some notification that the app currently requires the slightly "newer" login notifications to work.

We have an issue open to address that (#112), so I'm closing this one in favor of the old one - we really should just add legacy support.
