### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by lmontrieux** [TryGhost/Ghost-Desktop#127]
Trying to log in to my blog (Ghost pro), I get the 'Your password is incorrect' error, with a number of attempts remaining.

I have double- and triple-checked my password, it is definitely correct. Maybe the issue is that I have a long password, with a number of special characters?

**Comment by bnookala** [comment]
Hi @lmontrieux,

I'm looking into your issue right now; could you help out by providing a few details?

1. Your Operating System and version
2. The version of Ghost Desktop you've got installed
3. Is this message appearing on the *first* attempt to log into Ghost Desktop? (ie; have you ever been able to log into Ghost Desktop?)

I'm wondering if it's a Keytar issue. Keytar uses the native OS keychain to save your password and retrieve it when necessary. However, I suspect that it may not be the cause of this issue, as Ghost Pro users tend to have two different accounts: one for Ghost.org, and one for logging into the admin/blogging console of their Ghost Pro blog.

Additionally, the 'Your password is incorrect' string only appears within the Ghost codebase, not within Ghost Desktop's codebase.

Thanks!
Bhargav

**Comment by lmontrieux** [comment]
Hi @bnookala,

Thank you for looking into this, details are:
1. Mac OS X, 10.11.4
2. I'm using version 0.3.2 at the moment, though I had the same problem with the developer preview
3. Yes, this message appeared on my first attempt to log in, and has always appeared since then

Cheers!

**Comment by lmontrieux** [comment]
I also gave it a go on Windows 10, still with version 0.3.2 of Ghost Desktop. Same problem, I'm afraid.

**Comment by bnookala** [comment]
@lmontrieux can you try resetting your password via your Ghost instance's log in page? I highly suspect that this isn't a problem with Ghost Desktop. If your instance lives on Ghost Pro, you should be able to just go to the /ghost page on your blog to do that.

**Comment by lmontrieux** [comment]
That worked. I would swear I had tried it when running the developer preview, without success.
Thank you for looking into this!
