### ISSUE TITLE
Differing source code?

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Ghost-Desktop#128]
I was trying to see how the Notification is generated and wanted to see why the Error code is `undefined` for offline desktop and noticed this:

In `/Volumes/Macintosh HD/Applications/Ghost.app/Contents/Resources/app/dist/assets` for file `ghost-desktop.js`, 

the function is: 

```
 _handleLoadFailure(e, errorCode) {
            let errorDescription = arguments.length <= 2 || arguments[2] === undefined ? '' : arguments[2];

            let $webviews = this.$('webview');
            let path = requireNode('path');
            let errorPage = path.join(__dirname, '..', 'main', 'load-error', 'error.html');
            let validatedURL = e.originalEvent.validatedURL || '';

            if (validatedURL.includes('file://')) {
                return

...
```

instead of what i see from: https://github.com/TryGhost/Ghost-Desktop/blob/master/app/components/gh-instance-host.js#L144

I downloaded the source code for `v0.3.2` release and it tallies with the current latest code.. Any ideas?

**Comment by felixrieseberg** [comment]
We try to use pretty modern JavaScript, which is then transpiled down to a more compatible (and in many cases, also slightly smaller) version. You're looking at the same code, except that the version the app runs combines ES5 with the ES6 features supported by Electron, our runtime.

**Comment by kennethlimcp** [comment]
@felixrieseberg.. Interesting.. Sorry i'm a total noob in the web development world. :)

This is actually related to the issue where the Error code is undefined when there's no internet.. Seems like the function does not get the `c and s` argument while `e` corresponding to a `jQuery` object.
