### ISSUE TITLE
Removing a Ghost Blog does not actually remove it

### ISSUE THREAD

**Issue by bnookala** [TryGhost/Ghost-Desktop#135]
Steps to reproduce on Mac OS 10.11.3 running Ghost Development:

1. Add a blog
2. Remove aforementioned blog
3. Try to add aforementioned blog again (use *any* username or password)
4. Ghost Desktop automatically logs into the blog, despite the username or password being wrong.

**Comment by felixrieseberg** [comment]
Interesting development: We won't be able to fix this *precise* behavior (because Chromium keeps the session around - and I'd rather not log the user out before logging her/him back in), but I did find an error - we're never deleting the password when a blog is removed.
