### ISSUE TITLE
Automatically update download page

### ISSUE THREAD

**Issue by felixrieseberg** [TryGhost/Ghost-Desktop#142]
The download page currently requires manual updates whenever we release a new version. It's not a big deal, given that the app will *immediately* update itself once launched :rocket:, but ideally, we should probably have some kind of automatic mechanism that just points the download page at the latest release.

**Comment by ErisDS** [comment]
Would be quite nice to do this for Ghost itself as well, I still update it manually each time 😁 😁 😁

**Comment by felixrieseberg** [comment]
I'm closing this for now, given that I sent @aileencgn some JavaScripts to automatically update the downloads page.
