### ISSUE TITLE
Create Arch AUR package for Ghost Desktop

### ISSUE THREAD

**Issue by InAnimaTe** [TryGhost/Ghost-Desktop#143]
Any chance you can create a PKGBUILD and publish on the Arch Linux AUR? I'm an Arch user and would love a more official publishing of this program for easy installation on Arch ;)

**Comment by felixrieseberg** [comment]
Hey @InAnimaTe! Thank you so much for your interest in Ghost Desktop - the bad news is that we won't have the resources to accommodate ARCH Linux, given that the few people using Linux on the Desktop are mostly using Ubuntu.

I'm afraid that building the app yourself will be the only option for the foreseeable future - unless we get a lot more of these requests, of course.
