### ISSUE TITLE
Make Spell Checker Language Configurable

### ISSUE THREAD

**Issue by janiosarmento** [TryGhost/Ghost-Desktop#144]
Despite my initial expectations I've been using Ghost Desktop a lot.

However, there is something I hate in it: if you write in any language but English the spell checker goes crazy underlining every single word.

I'd suggest a setting in order to allow the user to choose whether enabling or disabling the spell checker, in case it is not possible to integrate the textatea with System's settings (I use OS X, but I'm aware there is only one codebase for all platforms).

Right now I enable Developer Tools (Current Blog), select the markdown textarea and modify its markup to `spellcheck='false'` before start writing. Not that hard, but non developers users might not think like me.

(As you can see I don't write in English, Portuguese is my main language.)

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! I'm sorry that you're having trouble - the system was really supposed to pick up your language and "just use that". Clearly this needs some work.

**Comment by janiosarmento** [comment]
Oops! My bad!

The system is picking the correct language from OS: I use my devices in English (don't ask).

However, I write content in Portuguese, despite my OS language. :)

Thanks for your prompt response.

**Comment by felixrieseberg** [comment]
Okay, new issue title then: Let's make you and everyone else choose their language in the preferences. Would that work for you? You'd need to have the dictionary installed in your operating system, but we could easily add a little drop-down 👍

**Comment by felixrieseberg** [comment]
Closing in favor of #145
