### ISSUE TITLE
Make Spell Checker Language Configurable

### ISSUE THREAD

**Issue by felixrieseberg** [TryGhost/Ghost-Desktop#145]
**Expected behavior** The spell checker continues to check for the system's default language. However, the preferences have a drop-down that enables the user to override the default settings, using the system's installed dictionaries.

It's important that not simply all possible languages are offered, but it is instead actually checked which dictionaries are installed. We'll otherwise enter misbehaving-spell-checker-land.

Ref #144

**Comment by flikteoh** [comment]
I have added auto-correct shortcut texts on my OSX. However, I noticed the App doesn't actually let OSX do auto-correct in it. Not sure if it's under the same issue as mentioned above.

**Comment by felixrieseberg** [comment]
@flikteoh: I'm afraid that that is currently not possible - we're using the dictionary that is inside OS X, but we sadly can currently not directly implement the fully native OS X spellchecker.

If any open source warriors would like to try this in the future, the whole [Electron community](https://github.com/electron/electron) would be very thankful to you.

I'm closing this issue now, since we do have a configurable spell checker now.
