### ISSUE TITLE
Blog behind basic auth not working

### ISSUE THREAD

**Issue by rapsli** [TryGhost/Ghost-Desktop#146]
I have a private blog setup that is protoected via basic auth. Unfortunately this does not seem to work.

`vendor.js:68722 Uncaught ReferenceError: process is not defined
C:\Users\Raphael\AppData\Local\ghost\app-0.4.0\resources\atom.asar\renderer\init.js:110 Uncaught TypeError: Cannot read property 'listeners' of undefined
file:///C:/Users/Raphael/AppData/Local/ghost/app-0.4.0/resources/app/dist/contributors.json Failed to load resource: net::ERR_FILE_NOT_FOUND
vendor.js:2756 Unhandled promise rejection Error: Cannot find module 'is-reachable'(…)(anonymous function) @ vendor.js:2756
vendor.js:2756 Unhandled promise rejection Error: Cannot find module 'is-reachable'(…)`

**Comment by felixrieseberg** [comment]
Ah, interesting use case - thanks for the info. Solution: We should allow you to disable the automatic login on a per-blog basis.

To fix this directly, could you try adding the blog with something like this `http://USER:PASSWORD@YOURBLOG.TLD`?

**Comment by rapsli** [comment]
I have tried this, but doesn't work either. It works though when on the browser

**Comment by felixrieseberg** [comment]
Thanks, we'll have to add a login dialog then.
