### ISSUE TITLE
UI preferences: zoom factor not applied on restart

### ISSUE THREAD

**Issue by abronan** [TryGhost/Ghost-Desktop#152]
*Very minor UI inconvenience here*:

If setting the zoom factor to a different value for the UI and then selecting "set zoom", the zoom factor is correctly applied.

The custom zoom factor value is correctly seen on restart but not applied thus requiring the user to go to the preferences and click on "set zoom" everytime.

(*setup*: OSX, Yosemite `10.10.5`, Ghost Desktop `v0.4.0`)

**Comment by bnookala** [comment]
Thanks for reporting! I'll take a look at this :)

**Comment by bnookala** [comment]
@abronan I *think* this has been fixed in the master branch of the repo. We'll probably roll out an update soon; look forward to it!

**Comment by abronan** [comment]
Awesome! Thanks for the update!
