### ISSUE TITLE
electron-rebuild / build-native-deps

### ISSUE THREAD

**Issue by dbhowell** [TryGhost/Ghost-Desktop#154]
This is a query more than an issue: referencing the dev setup (https://github.com/TryGhost/Ghost-Desktop/blob/a360ecca457ad29d88ec3dc8303f7bef38ed94ce/docs/developer-environment.md), it suggests running `npm run build-native-deps-64` (or -32) which explicitly runs with `-w keytar`. Does that mean only keytar module is compiled?

The reason I ask is that I had to run `electron-rebuild` with no parameters to ensure `spellchecker` is also compiled. I can also confirm running `electron-rebuild` without the -w parameter, both `keytar` and `spellchecker` were built.

**Comment by felixrieseberg** [comment]
You're totally right. That should be fixed.

**Comment by dbhowell** [comment]
Great. I've got a branch on-the-ready. Will PR soon.
