### ISSUE TITLE
when insert an emoji to the article, it occur an error

### ISSUE THREAD

**Issue by royburns** [TryGhost/Ghost-Desktop#155]
![image](https://cloud.githubusercontent.com/assets/652375/15812442/a08cb054-2be7-11e6-8b6f-5ce597baf7b5.png)

**Comment by felixrieseberg** [comment]
Hey, I can add emojis just fine - what you see there looks more like a database error. Could you do me a favor and try entering an emoji using Google Chrome?

**Comment by royburns** [comment]
Saving failed.
update `posts` set `author_id` = '1', `created_at` = '2016-06-16 05:05:22.000', `created_by` = 1, `featured` = false, `html` = '
😁

', `id` = '83', `image` = NULL, `language` = 'en_US', `markdown` = '😁', `meta_description` = NULL, `meta_title` = NULL, `mobiledoc` = NULL, `page` = false, `published_at` = NULL, `published_by` = NULL, `slug` = 'untitled-2', `status` = 'draft', `title` = '(Untitled)', `updated_at` = '2016-06-16 05:05:28.985', `updated_by` = 1, `uuid` = 'b26a8ffe-e710-46c9-97e0-3f557740f648', `visibility` = 'public' where `id` = '83' - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x98\x81

**Comment by royburns** [comment]
yes， i can enter an emoji using google chrome

![Uploading image.png…]()

**Comment by royburns** [comment]
ghost: 0.8.0
ghost client(MacOS):0.4.0

**Comment by royburns** [comment]
i see, i use utf-8 which not support emoji, i need to switch utf8 to utf8mb4.

**Comment by felixrieseberg** [comment]
Thanks for reporting - it seems like you figured out where the error is.
