### ISSUE TITLE
Export blog causes loading failure

### ISSUE THREAD

**Issue by kevinSuttle** [TryGhost/Ghost-Desktop#162]
![ghost-blog-export-crash](https://cloud.githubusercontent.com/assets/95672/16160423/0c487a2e-3496-11e6-86a2-eaa6217801a6.gif)

**Comment by bnookala** [comment]
Hey!

Thanks for reporting this - I can definitely reproduce it on my own. It appears as though this might be related to Ghost itself, as I'm seeing an authorization error when the blog attempts to reload. This is the event that gets passed through to the error handler:

<img width="1533" alt="screenshot 2016-06-24 12 16 15" src="https://cloud.githubusercontent.com/assets/87996/16346655/b42aafcc-3a05-11e6-952d-b6c6f33b102f.png">

Opening that "authorized" url in my own browser yields this JSON blob:

```{"errors":[{"message":"Access denied.","errorType":"UnauthorizedError"}]}```

I'll keep digging though.

Bhargav

**Comment by felixrieseberg** [comment]
This is now working in 0.6.
