### ISSUE TITLE
Drag and drop of images doesn't work

### ISSUE THREAD

**Issue by kevinSuttle** [TryGhost/Ghost-Desktop#163]
Pretty sure this can be enabled via Electron.

**Comment by felixrieseberg** [comment]
Yep, that's a bug. I'll work on that.

**Comment by kevinSuttle** [comment]
Woot. Thanks!

**Comment by kevinSuttle** [comment]
How do users check for updates? Does an alert just pop up?

**Comment by felixrieseberg** [comment]
We push updates automatically, but a new release with the fix isn't out yet. I'll make sure to push one tomorrow, though!

**Comment by kevinSuttle** [comment]
Awesome, thanks again!
