### ISSUE TITLE
"flickering" while typing at the end of post

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Ghost-Desktop#166]
It's hard to put a proper description so feel free to edit the title!

The screen capture demonstrates the issue best :)

https://dl.dropboxusercontent.com/u/36134145/0.4.0-flickering.mov

**Comment by felixrieseberg** [comment]
Hey! I'm not totally sure what is going on here, but I'm noticing that the image on the right (in the preview) has the trashcan visible.

I'm not 100% convinced that this is a Ghost Desktop issue, we might have to punt this over to https://github.com/TryGhost/Ghost-admin. @ErisDS: Any thoughts?
