### ISSUE TITLE
Please add RTL language support like Arabic.

### ISSUE THREAD

**Issue by koubeex** [TryGhost/Ghost-Desktop#178]
Arabic doesn't alligne to the right side when you write.
and it gets messed up of you use markdown.

**Comment by ErisDS** [comment]
Hey there @koubeex! Ghost doesn't support RTL languages at present, so the Desktop app is not able to support it either. If you'd like to find out more, there was talk about this recently on the [Ghost repository](https://github.com/TryGhost/Ghost/issues/7103). RTL / Arabic support is still not something that's been asked for or got any traction over on our [wishlist](http://ideas.ghost.org) so I'd recommend raising this there to start with :)

**Comment by mistriel** [comment]
Hi,
@ErisDS i think that minimal support for RTL is valuable feature.
By minimal i mean - just the typing direction of the editor HTML page.
Regarding font support - i would suggest to ignore it, as users that usually consume RTL content will have browser with suitable fonts.
WDYT ?
The link to wishlist is broken.
