### ISSUE TITLE
Loading animation is off-center

### ISSUE THREAD

**Issue by felixrieseberg** [TryGhost/Ghost-Desktop#184]
Probably happened in one of the last commits:

![screen shot 2016-08-06 at 10 44 57 am](https://cloud.githubusercontent.com/assets/1426799/17458359/e664b5d0-5bc2-11e6-8ba3-7cf98128adb1.png)

**Comment by felixrieseberg** [comment]
This magically fixed itself?

**Comment by kennethlimcp** [comment]
@felixrieseberg maybe not?

Ghost Desktop Version: 0.7.0
Ghost Blog Version: 0.9.0


<img width="1280" alt="screen shot 2016-09-04 at 20 42 40" src="https://cloud.githubusercontent.com/assets/6760914/18384365/b21cfb24-76bc-11e6-8931-7976bd60a7d2.png">
