### ISSUE TITLE
Whats the blog for - bug

### ISSUE THREAD

**Issue by itahmid** [TryGhost/Ghost-Desktop#188]
cant figure out the blog thing... why do you  need my blog...
tried with my fb, tw and even my dead blogger page, nothing seems to work!!!!

**Comment by acburdine** [comment]
Hey @itahmid, sorry to hear you're having trouble!

The Ghost-Desktop project is designed to be used only with the blogging platform Ghost ([github project](https://github.com/TryGhost/Ghost), [website](https://ghost.org)), meaning that if you don't have an actual Ghost blog set up, then the desktop application won't work 😄 

Sorry about the confusion, and let us know if you have any other questions!
