### ISSUE TITLE
Blog Configuration will not allow http connections

### ISSUE THREAD

**Issue by chuckdee68** [TryGhost/Ghost-Desktop#191]
Whenever I set up the blog for http instead of https, the blog address outlines in red.  I can't connect via https, and was always able to connect via http before.

**Comment by felixrieseberg** [comment]
Hey @chuckdee68, sorry to hear you're having trouble! http:// connections should be perfectly fine - would you mind sharing the exact URL you're trying to enter?

**Comment by chuckdee68** [comment]
http://chuckdee.net/ghost.  When I enter it, it's fine.  When I click save, it starts to save, then the textbox for the URL outlines in red.  This works if I use https, but I can't connect to my blog using https.

**Comment by felixrieseberg** [comment]
Huh, weeeeeeird! If you go to About - About Ghost, what version do you see? I'm only asking because I can add your blog just fine (I can't login obviously). I'm asking because I'm wondering if you're stuck on an older version - if so, maybe downloading Ghost 0.6 would fix your issue.

**Comment by chuckdee68** [comment]
I downloaded 0.6 just to make sure (I originally tried to install it using chocolatey), but that didn't help.  The version in the preferences says 0.6.0, however, I noticed after you asked, that I don't have an About.  The only thing on my help menu is learn more.  I've tried to uninstall 0.6.0 and reinstall it, but no joy there either.

**Comment by Mnw2212** [comment]
I have been trying the same thing and face the exact same issue.
The difference , however was the URL.
I am trying to add the default ghost localhost url
http://localhost:2368/

**Comment by dkekish** [comment]
Just trying it out and a new fresh install on localhost:2368 won't allow me past the the Add blog screen.
