### ISSUE TITLE
Unable to maximize Ghost on Pantheon desktop

### ISSUE THREAD

**Issue by ruppalsingh** [TryGhost/Ghost-Desktop#193]
I'm not certain what is at fault here, but I guess one has to start somewhere.

I do not have the option to maximize the window on the desktop application.
- Double clicking the window title doesn't do the trick.
- The option to maximize is blacked out on right clicking the window title.

I'm running elementaryOS Freya (0.3.2 x64) on Pantheon desktop (default). I do not have any computer running Ubuntu 14.04 LTS so I can't test it as such.

**Comment by bnookala** [comment]
Hi @ruppalsingh: thanks for letting us know! Unfortunately, we don't have the bandwidth to look into every variation of window management systems that exist out there, so we very likely won't be able to look into it in the near term. As always, we'd love any help here - so if you can figure out what's causing the issue, a pull request with a fix would be very appreciated :)

**Comment by ruppalsingh** [comment]
I have not worked in Electron yet, but if at some point in the future, I do so, I will be happy to try and troubleshoot this. :)

**Comment by dbhowell** [comment]
Just an FYI, I am using elementaryOS Loki (0.4 x64) and this issue does not exist. I can see and use the maximise button and clicking the title bar does maximise & restore.

Perhaps check the eOS 'Tweak Tool'.

Ultimately I don't think it is an Electron/Ghost-Desktop issue.
