### ISSUE TITLE
Move updater URL to HTTPS

### ISSUE THREAD

**Issue by jloh** [TryGhost/Ghost-Desktop#199]
I know the packages are signed (for windows at least) but the updater URL is still only available over HTTP, HTTPS just flat out fails. Are packages for OSX signed, or just Windows?

If it isn't possible to put the updater URL on HTTPS at this point could a setting please be added to disable automatic updates?

**Comment by felixrieseberg** [comment]
Seems totally reasonable, we should do that. To put your mind at ease for now - the updates *are* signed with a full code signing certificate, unsigned or incorrectly signed updates will not be installed.

But again, yes, that should be a thing.

**Comment by felixrieseberg** [comment]
To give you a quick update: We're on it :fire:

**Comment by jloh** [comment]
Any update on this one?

**Comment by jochenkirstaetter** [comment]
Any news here?

**Comment by jloh** [comment]
Should be good to close this one off now that updates are sourced via electron.org!

**Comment by felixrieseberg** [comment]
Sorry for not closing & thank you for staying on the ball!
