### ISSUE TITLE
Ghost Electron Spec

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost-Desktop#2]
Following up from the [announcement blog post](https://dev.ghost.org/desktop-app/), it would be great to get a sense of who might be interested in leading development on this - and starting to figure out a very broad initial spec/approach!

I don't know why I said "let's talk about this in the comments" on the post, Github makes way more sense.

We have no lead devs on this, so there is plenty of room for anyone to have a really significant impact if you have the time and inclination. Of course the Ghost core team and foundation are also happy to support you in any way that we can :)

**Comment by JohnONolan** [comment]
Ping @felixrieseberg / @luin / @BlueHatbRit

**Comment by luin** [comment]
Just tried the native OS X app. It's great to be able to manage multiple blogs within a single app. Despite of this feature, it seems pretty easy to write a wrapper with Electron. I can write a demo in this weekend so that we can see whether this is what we want.

**Comment by BlueHatbRit** [comment]
I've not used Electron for anything serious yet but have good experience in Node and Desktop/Mobile apps are my forte so I'd love to have a hand in anything we come up with. The OSX app looks pretty cool so far, as @luin said, multiple blogs is a great feature that'll probably be one of the biggest reasons to use it imo.

What sort of thing were you thinking for the demo @luin?

**Comment by luin** [comment]
We may start with building an Electron app similar to the current native one with some fixes:

1. Some links can't be opened (for instance, the "VIEW BLOG" link).
2. Add a title bar for the window so that the app is easier to be moved.

**Comment by BlueHatbRit** [comment]
I think that's a sensible direction, is there anything else that's missing that we think is a higher priority or a technical challenge we need to prove / figure out before we re-create this version in Electron?

**Comment by felixrieseberg** [comment]
Hey everyone! I have a decent amount of experience with Electron (built a few apps, worked on Electron/Brightray core) and I'm happy to move this forward.

Before we dive into anything, we should probably talk features and (a bit) about the spec - given that Sqlite & Knex (used by Ghost's backend) run super-well in Electron, we should be able to do some fancy offline capabilities. That being said, going with a more simple "writing while online only" desktop app would obviously be easier - and we'd get a v1 out the door sooner. Either way, [Ember-Electron](https://github.com/felixrieseberg/ember-electron) and Paul Bett's tool should make this fairly easy.

**Comment by luin** [comment]
Hi @felixrieseberg! Offline support would be extremely useful. I didn't think of that 😄. For the first version, I think using `<webview />` tag to embed the Ghost admin page should do the trick, so that we don't need to deal with Ember.js at this stage.

**Comment by felixrieseberg** [comment]
That's a common thing people do with Electron, but I'm traveling the world trying to push people beyond that: It's fairly easy to throw together, but there's no value for the user - I'd actually argue that the implicit security risks, the unnecessary runtimes, and the additional resource usage wouldn't do the Ghost brand much service. There's so much more we can do with only a little bit more work.

My proposal, for now: John and I are gonna have a quick chat about what can and can't be done (there's a bunch of stuff that should be fairly lightweight and easy to do), then we write a neat spec, followed by all of us building a beautiful Ghost Desktop app right after ✨.

**Comment by luin** [comment]
Aha, I got the point. That would by great!

**Comment by BlueHatbRit** [comment]
:+1: I'd also lean towards doing something more specific to Electron rather than a webview, I think we'd get more benefits from it and also open the doors a bit more to future improvements. It does mean a bit more of a ramp up but I don't see that really being a problem.

I'd also probably be tempted to go with an online only version first purely to get something going faster that people could start using and we could get some feedback quicker.

A spec would be great to have! I'd also appreciate a brief chat about the basic architecture just to ensure we're all on the same page before we start, but that's probably just me as the most inexperienced electron dev here (I think).

Look forward to seeing the spec!

**Comment by felixrieseberg** [comment]
Hey everyone,

after chatting with John, we came up with a few core themes that we want to follow with (the now named) Ghost Desktop. 

 * The development experience should be as close to TryGhost/Ghost as possible - Ghost made a bunch of smart choices around developer experience and productivity, which should carry over to Ghost Desktop as much as possible.
 * Ghost Desktop should make use of its additional native powers as much as possible.
 * Ghost Desktop should be the go-to tool for power users who have to manage multiple blogs, giving them an edge over a browser with a bunch of tabs open.

To follow those themes, here are some technical choices I made:

 * Ember 2.3.0: One could make a reasonable argument that Ember is a little bit overkill, but given that every Ghost contributer knows the Ember innards inside-out, people can easily work on both projects. In addition, we can re-use existing Ember Ghost components.
 * [Ember-Electron](https://github.com/felixrieseberg/ember-electron): Wraps our little Ghost Desktop Ember app in a lot of Electron padding.
 * [Ember-Local-Storage](https://github.com/funkensturm/ember-local-storage): Proven addon that manages `localStorage` really well, enabling us to use Chromium's database. (This will not be used or helpful with caching blogs, should we do that in the future).
 * Testing, Code Style: Let's just use whatever Ghost Admin is already using.

#### How to go forward from here?
I spent the last two days building a prototype that already works fairly well (given the small amount of time).

![screen shot 2016-02-23 at 4 31 16 pm](https://cloud.githubusercontent.com/assets/1426799/13271595/e245b868-da4a-11e5-977c-eacaaa81fc75.png)

There's obviously a lot of work between where we are now and where we should be before we ask users to give it a try - I'll make a bunch of issues, all of them up for grabs. I made a basic contributors guide, but I'll flesh that out over the next couple of days, too. We'd love help!

I will also presenting [Ember-Electron on Saturday in the Global Ember Meetup](https://www.bigmarker.com/global-ember-meetup/S02E03-Ember-gets-hardcore), but if any of you have any questions about Electron (or how it works together with Ember), feel free to ping me directly!

Thank you!

**Comment by JohnONolan** [comment]
So excited! :dancer:

**Comment by BlueHatbRit** [comment]
Fantastic work so far, I'm just going to pull down the current version you've done and see what's what but the aims look great. May be worth throwing them onto a wiki page for easy access of new contributors? I like the idea of sticking with ember, it makes a lot of sense for the reasons you've stated.

Sadly I've got no internet at home right now but I've cloned the repo to have a look through this evening. Then I'll look at picking up some of the issues and we can start going from there. Do we have a list of features that we'd be aiming for in a v1 release?

**Comment by GQAdonis** [comment]
I am in and have forked the project!  I will look at the issues, etc., pick things off and submit pull requests. This is really cool stuff!

**Comment by felixrieseberg** [comment]
@BlueHatbRit: Totally with you - wiki pages are great, but I'll probably just throw it into the contributing.md (at least for now). I'll spend the next two days creating issues, labelling them either as `0.1.0` (for the first release) or `next` (meaning that it'd be cool to have, but shouldn't block our first release). Thanks for joining us!

**Comment by BlueHatbRit** [comment]
Great, the issues will give us some good direction, look forward to seeing them pop up!

**Comment by Thirunavukkarasu** [comment]
I'm a JavaScript developer who is working currently with frameworks AngualrJS and ExtJS. I'm just wondering is there any possible way for me to contribute to this project!!

**Comment by felixrieseberg** [comment]
Hey @Thirunavukkarasu! Of course, help is always very welcome - we have a bunch of volunteers working on this project (I myself for instance just :heart: Ghost). There are two easy ways of contributing:

* Pick one of the open issues - comment that you'll work on it and feel free to ask for help whenever you want it.
* If you want to add a new feature, add an issue first to make sure that it fits into the plan, then make a PR and feel free to ask for help whenever 👍
