### ISSUE TITLE
Ensure proper encoding in menus

### ISSUE THREAD

**Issue by felixrieseberg** [TryGhost/Ghost-Desktop#200]
![image](https://cloud.githubusercontent.com/assets/1426799/18350858/b88ac2d8-758c-11e6-8ecb-73fe75624f63.png)

**Comment by balajikandasamy** [comment]
I am trying to reproduce the issue in Windows 10 and not seeing it. Is this specific to OS X any directions will help me fix the issue.

**Comment by felixrieseberg** [comment]
Yeah, we may have fixed this somewhere along the way 🤔
