### ISSUE TITLE
Weird <html></html> error

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Ghost-Desktop#201]
Ghost Desktop version: 0.7.0
Ghost Blog version: 0.9.0

<img width="1280" alt="screen shot 2016-09-09 at 18 33 41" src="https://cloud.githubusercontent.com/assets/6760914/18384292/52d15534-76bc-11e6-9f2f-36a58952a94a.png">

**Comment by felixrieseberg** [comment]
Given how nobody else reported this, I'm, hoping that we're looking at a one-off somewhere in Ghost (Core). I'm closing this for now, because we couldn't really find anything...

In case you're still around: Did this error pop up every single time you opened Ghost in the app, but not in a browser?

**Comment by kennethlimcp** [comment]
Hmm i switched to Ghost Desktop app blogging ever since it is available so i don't have a clue. My Ghost is now 0.11.0 and i'll report again if there's the issue! :)
