### ISSUE TITLE
Contribution guide outdated and build failure

### ISSUE THREAD

**Issue by balajikandasamy** [TryGhost/Ghost-Desktop#215]
I am willing to contribute tried setting up the dev env by following the guide and the documentation seems outdated. I managed to go through the package.json to run the script. I am getting a build error. My environment is Windows 10, VS2015 Enterprise, Python27, Node 6.9.1, npm 3.10.8

npm Logs
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ghost-desktop@0.7.0~prebuild: ghost-desktop@0.7.0
6 silly lifecycle ghost-desktop@0.7.0~prebuild: no script for prebuild, continuing
7 info lifecycle ghost-desktop@0.7.0~build: ghost-desktop@0.7.0
8 verbose lifecycle ghost-desktop@0.7.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle ghost-desktop@0.7.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Opensource\Ghost-Desktop-master\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\bkandasamy\AppData\Roaming\npm;C:\Program Files\Python27\
10 verbose lifecycle ghost-desktop@0.7.0~build: CWD: D:\Opensource\Ghost-Desktop-master
11 silly lifecycle ghost-desktop@0.7.0~build: Args: [ '/d /s /c', 'grunt build' ]
12 silly lifecycle ghost-desktop@0.7.0~build: Returned: code: 6  signal: null
13 info lifecycle ghost-desktop@0.7.0~build: Failed to exec build script
14 verbose stack Error: ghost-desktop@0.7.0 build: `grunt build`
14 verbose stack Exit status 6
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ghost-desktop@0.7.0
16 verbose cwd D:\Opensource\Ghost-Desktop-master
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error ghost-desktop@0.7.0 build: `grunt build`
22 error Exit status 6
23 error Failed at the ghost-desktop@0.7.0 build script 'grunt build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ghost-desktop package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     grunt build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ghost-desktop
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ghost-desktop
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by balajikandasamy** [comment]
I did try npm start and log below. I am a beginner so apologize if I have missed any basics in setting up the environment.

D:\Opensource\Ghost-Desktop-master>npm start

> ghost-desktop@0.7.0 start D:\Opensource\Ghost-Desktop-master
> grunt shell:fetchContributors && ember electron

Codesigning certificate can not be found, release build will fail
To fix, set CODESIGN_CERTIFICATE
Codesigning password can not be found, release build will fail
To fix, set CODESIGN_PASSWORD
Running "shell:fetchContributors" (shell) task

Done.

Build successful - 14987ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 2967ms
Babel                                         | 2933ms
Babel                                         | 1733ms
Babel                                         | 830ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (12)                                    | 9026ms (752 ms)

--------------------------------------------------------------------
Ember Inspector running on http://localhost:30820
Open the inspector URL in a browser to debug the app!
The inspector is also available as an addon inside your
app's developer tools.
--------------------------------------------------------------------
Starting Electron...
--------------------------------------------------------------------
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\Opensource\Ghost-Desktop-master\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (D:\Opensource\Ghost-Desktop-master\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
Electron exited.

**Comment by bnookala** [comment]
@balajikandasamy What happens when you try and run `grunt build` in the directory?

**Comment by bnookala** [comment]
Also, as per this guide https://github.com/TryGhost/Ghost-Desktop/blob/master/docs/developer-environment.md, you may be missing the `grunt-cli` global dependency. Try and install it with `npm install -g grunt-cli`, then re-run the build steps.

**Comment by balajikandasamy** [comment]
I did install grunt-cli. I get this error when running grunt build

Codesigning certificate can not be found, release build will fail
To fix, set CODESIGN_CERTIFICATE
Codesigning password can not be found, release build will fail
To fix, set CODESIGN_PASSWORD
Running "shell:fetchContributors" (shell) task

Running "shell:build" (shell) task
'ember' is not recognized as an internal or external command,
operable program or batch file.
Warning: Command failed: ember electron:package --environment production --arch x64 --platform win32 --app-version 0.7.0 --overwrite
'ember' is not recognized as an internal or external command,
operable program or batch file.
 Use --force to continue.

Aborted due to warnings.

**Comment by balajikandasamy** [comment]
I was able get over the issue cleaning up and starting from the scratch. I did notice only npm run script name was wrong updated the same and created a pull request for it.

**Comment by felixrieseberg** [comment]
@balajikandasamy first of all, thank you so very much for taking enough interest to not only try our outdated guides, but then to also open an issue *and* fix them. Outstanding work and I'm so very happy that you want to help us out - we're all volunteers here, so the more the merrier <3

I think we can close this (for now, you might stumble over stuff), but again, welcome!

**Comment by balajikandasamy** [comment]
Thanks for the warm welcome. I will pick some beginners issues and go from there.
