### ISSUE TITLE
What to write in https://myblog.com/ghost 

### ISSUE THREAD

**Issue by rashmireddyp** [TryGhost/Ghost-Desktop#234]
I am not getting what to write in the input box https://myblog.com/ghost in my desktop application.

**Comment by bnookala** [comment]
hi @rashmireddyp, Ghost Desktop requires that you have a ghost.org blog set up or a self hosted Ghost blog. Do you have an existing ghost blog somewhere? You can use the URL to your blog in the  input box.

**Comment by rashmireddyp** [comment]
Yes, i have done with the setup in my desktop thank you for your help. 
Link: https://mylearnings-2.ghost.io/

**Comment by bnookala** [comment]
@rashmireddyp Awesome, glad to hear that you were able to resolve your issue. I'll close this issue for now.
