### ISSUE TITLE
Upgrade Notification should say something other than "Ghost-Core"

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-Desktop#236]
From https://github.com/TryGhost/Ghost/issues/7849

![image](https://cloud.githubusercontent.com/assets/5167581/21973773/a48d08f6-db88-11e6-84df-fe7be7ee02f5.png)

> This should read "Ghost" - rather than "Ghost Core". We don't need to pass the burden of understanding what "Core" means onto the end-user. - @JohnONolan 

Personally I agree with not saying "ghost-core," as it might be hard to understand for end-users, but I'm not sure if just saying "Ghost" is clear enough. Posting this issue here for further discussion 😄

**Comment by felixrieseberg** [comment]
I shall be changing it to "Ghost for your Blog". We introduced the change because we received multiple issues from people saying "What do you mean, there's an update? I thought this thing auto-updates?".

**Comment by JohnONolan** [comment]
Hmmm -- that actually makes some sense, and I don't have a better alternative RN. Closing until a better solution presents itself!
