### ISSUE TITLE
App does not quit properly on Windows

### ISSUE THREAD

**Issue by tornography** [TryGhost/Ghost-Desktop#239]
Hi,

there is a problem starting ghost in version 1.2.0 on Windows 10 after installation.

The instellation works as expected. Afer the installation has finished ghost starts the first time.
But afterwards I am not able to start ghost again. (Icon, Starmenu, ...)

Regards,
Manuel

**Comment by felixrieseberg** [comment]
I've seen this before - if you keep trying, it should eventually start Ghost. I think this is a case of an icon gone rouge, but I have so far trouble figuring out what is exactly going wrong.

**Comment by felixrieseberg** [comment]
...actually, I think the issue might be that Ghost doesn't quit.

**Comment by jochenkirstaetter** [comment]
Hi,

We use the following code to explicitly close / destroy the window:

win = new BrowserWindow({})  // blah parameter in constructor

  // Emitted when the window is closed.
  win.on('closed', () => {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    win = null;
  });

Will give it a shot these days, and maybe able to provide a PR.

**Comment by jochenkirstaetter** [comment]
Also, I have noticed that the closing behaviour of applications might depend on the OS:

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

Ghost Desktop doesn't differentiate between OSes.

**Comment by jochenkirstaetter** [comment]
Hi @felixrieseberg 

Ghost Desktop closes perfectly on Windows (and Linux - tested). This issue might be closed then.

Regards, Jochen
