### ISSUE TITLE
Hide private blog password in settings

### ISSUE THREAD

**Issue by jawn** [TryGhost/Ghost-Desktop#254]
Given a blog with password protection enabled.

Steps:
- open Ghost Desktop
- go to Settings > General  > Make this blog private

Expected result:
- password should be hidden by default. Optionally provide means to show password.

Actual result:
- previously specified password is clearly visible.

Motivation:
- walking through settings in an open environment or during a presentation should be possible without revealing password info by accident.

**Comment by jawn** [comment]
Moreover, I would expect that passwords in a safe way, eg with proper hash applied.

**Comment by ErisDS** [comment]
Hi @jawn, this is a deliberate choice and how the feature works in Ghost core. It's not anything to do with the Desktop app. You can read my reply to a similar concern over here: https://github.com/TryGhost/Ghost/issues/5512
