### ISSUE TITLE
Add Ghost Blog Markdown Guide

### ISSUE THREAD

**Issue by MaXFalstein** [TryGhost/Ghost-Desktop#255]
Ghost Desktop has the tiny Markdown Help page available at the bottom of the article the user is authoring. This is good, but it misses out lots of possibilities. These are linked at the bottom of the Markdown Help, but for the people who want to stay within Ghost Desktop, it takes the user to the browser.

I think users would benefit from adding the [Markdown Guide](https://help.ghost.org/hc/en-us/articles/224410728-Markdown-Guide) to the Ghost Desktop.

I have briefed @felixrieseberg for what I am thinking of:

![ghost app w markdown guide](https://cloud.githubusercontent.com/assets/1693762/22698404/63538cd6-ed4c-11e6-8a66-d978248b6c10.png)

The above image does not show the full [Markdown Guide](https://help.ghost.org/hc/en-us/articles/224410728-Markdown-Guide) web page.

I welcome ideas for what users would like to do with this proposed feature addition.

**Comment by JohnONolan** [comment]
We have added this in Ghost 1.0 - feel free to test out the beta :) https://github.com/TryGhost/Ghost/releases/tag/1.0.0-beta.2
