### ISSUE TITLE
Icon of DMG file

### ISSUE THREAD

**Issue by yoonsikp** [TryGhost/Ghost-Desktop#257]
The icon of the dmg file should be that of a disk image with the ghost logo superimposed on it, not the actual logo of the app itself. This becomes confusing as the disk image on the desktop can become confused with the actual app itself. I've attached a sample image of a disk image that respects this rule.

![screen shot 2017-02-12 at 10 04 47 pm](https://cloud.githubusercontent.com/assets/1870062/22869751/49f7ade0-f16f-11e6-83e2-8411bcb401ca.png)

**Comment by felixrieseberg** [comment]
Hey! Thank you for giving the app a try - and your suggestion. While there's no rule as to what the image has to look like, I think it's a good idea.

Would you be interested in giving it a go? I'd love to see a pull request!

**Comment by JohnONolan** [comment]
PR already merged
