### ISSUE TITLE
Dark/Night Theme

### ISSUE THREAD

**Issue by docrinehart** [TryGhost/Ghost-Desktop#268]
I use browser stylesheets to color most of the web apps I use with a dark theme since I spend a great deal of time in front of them. I think not having a dark theme for the ghost desktop app is probably the only thing that's kept me from using it regularly.

As an aside, if I can find the time, I'd be happy to fork it and submit a PR if someone doesn't pick this up first. Thanks.

**Comment by felixrieseberg** [comment]
That's a pretty good idea. We can totally pre-load CSS - we could add a new field to our preferences (something like `Custom CSS`). Once the app starts, [we could use this method](https://github.com/TryGhost/Ghost-Desktop/blob/master/app/components/gh-instance-host.js#L131) to preload an additional file (if the setting exists).

I'd 😍 to see a PR!

**Comment by docrinehart** [comment]
Oh wow... That could even open it up more. A dark would be a good included option, but you could even extend it to allow theming for the editor.

**Comment by felixrieseberg** [comment]
Yeah, I'm into it. Feel free to open the PR early (as a WIP), I'm happy to support this.

**Comment by JohnONolan** [comment]
This was added in Ghost 1.0 -- feel free to test the beta :) https://github.com/TryGhost/Ghost/releases/tag/1.0.0-beta.2 

The feature is located under the "labs" settings area

**Comment by docrinehart** [comment]
@JohnONolan So this will apply to both the web and desktop applications?
