### ISSUE TITLE
Provide an AppImage

### ISSUE THREAD

**Issue by Jcambass** [TryGhost/Ghost-Desktop#270]
Wouldn't it be great to be able to install Ghost Desktop on virtually any major distro?
I think something like an AppImage would really be a nice idea!

Edit: This should be quit easy for electron apps:

> Use electron-builder. This option might be the easiest if you have an Electron-based application. In this case, you define AppImage as a target for Linux (default in the latest version of electron-builder) and in many cases are done with the AppImage generation.

https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages

**Comment by JohnONolan** [comment]
Unless someone is suggesting that they are going to actively create and maintain this - it's not something we're going to track :)
