### ISSUE TITLE
extra files such as .git in themes cause an error

### ISSUE THREAD

**Issue by nebulousdog** [TryGhost/Ghost-Desktop#272]
When zipping a theme to upload, the `.git` repo file causes an issue. I assume this happens for other filetypes too that weren't expected.

![screenshot_2017-05-14_10-00-11](https://cloud.githubusercontent.com/assets/2218331/26036083/26be1c92-388c-11e7-8605-fe81d485f24b.png)

```
EISDIR: illegal operation on a directory, unlink '<stuff>/<theme-name>/.git'
```

**Comment by ErisDS** [comment]
This was an issue with [gscan](https://www.npmjs.com/package/gscan) our tool for validating themes. It was fixed in the recent [0.11.9](https://github.com/TryGhost/Ghost/releases/tag/0.11.9) release of Ghost - it is nothing at all to do with Ghost Desktop 👻
