### ISSUE TITLE
Autoupdater not running on 1.2.0

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Ghost-Desktop#275]
Is there some way i can debug and see if the auto updater is kicking in to download a newer version (`1.3.0`)

**Comment by akshaybabloo** [comment]
I have the same problem

**Comment by kennethlimcp** [comment]
Running with `sudo open /Applications/Ghost.app` didn't work as well

**Comment by felixrieseberg** [comment]
Dang. Auto-updating is hard, but that's too many reports. Which operating system are y'all on?

**Comment by kennethlimcp** [comment]
Mac Osx El Capitan

ken
sent on mobile

**Comment by akshaybabloo** [comment]
I'm on windows

**Comment by JohnONolan** [comment]
Doesn't work for me either - OSX Sierra 10.12.5

**Comment by felixrieseberg** [comment]
Well, I did some research and I'm afraid that we broke auto-updates - again. I'm so sorry. Basically, here's what happened:

• We're using `is-reachable` to detect if the remote update server is actually reachable
• Then, we update

Somehow, I managed to sneak an update to `is-reachable` in that changes it from Node's callback-style to a promise - meaning that `is-reachable` never returns and we never actually check for an update 😢

**Comment by felixrieseberg** [comment]
Quick comment on what we'll do about this:

:one: Obviously, we'll fix the root cause (#281)
:two: Also, we'll add more debugging statements to the auto-updater and add a simple button that forces an update check, bypassing everything else (#282).
