### ISSUE TITLE
Add version software version number

### ISSUE THREAD

**Issue by akshaybabloo** [TryGhost/Ghost-Desktop#277]
I think it would be nice if you add the version number somewhere in `preferences` or create an about pop-up window and added it there.

**Comment by JohnONolan** [comment]
Already exists both for the site and desktop app:

![image](https://user-images.githubusercontent.com/120485/27966399-0113a20c-6337-11e7-8692-2bec413300c1.png)

**Comment by akshaybabloo** [comment]
Not in windows

**Comment by jochenkirstaetter** [comment]
Not available on Linux
