### ISSUE TITLE
Better desktop compatibility for 1.0 night-shift

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost-Desktop#279]
Ghost 1.0 introduces a night-shift option to turn the UI dark and mystical. For better compatibility with the dual colour schemes, it would be helpful to change the BG of `.switcher` to `#152025`

Currently this seems to be overridden sometimes by

```
.switcher.is-vibrant {
   background-color: inherit;
}
```

I'm not sure what that's for - but it doesn't look right

**Comment by felixrieseberg** [comment]
Neat! The inherit is currently there to ensure that vibrancy (that frosted transparency on macOS) works. You're the one with the design instinct, should we just kill vibrancy?

It's pretty cool, but it's also fairly CPU-hungry.

**Comment by JohnONolan** [comment]
yeah I'd kill it - also switcher.is-vibrant only seems to happen when developer tools is open. I can literally toggle it on/off with cmd+shift+i 🤗

**Comment by JohnONolan** [comment]
wrong button fml
