### ISSUE TITLE
Linux: Main Window not resizable

### ISSUE THREAD

**Issue by jochenkirstaetter** [TryGhost/Ghost-Desktop#284]
Hi,

Ghost Desktop on Linux doesn't allow to resize the application window; compared to Windows.
Only options available are:
- Minimize
- Maximize
- Full Screen mode (F11)

Using Ghost Desktop 1.3.0 on Xubuntu 17.04 64bit

**Comment by jochenkirstaetter** [comment]
Okay, my mistake...

The window itself is resizable but the values of minHeight and minWidth should be reviewed. I'm currently running Ghost Desktop on 1280x800 resolution. Also, a lot of laptops have a native screen resolution of 1366x768 which wouldn't provide enough real-estate to display the Ghost Desktop properly.

**Comment by dpeeps74** [comment]
I have this issue too. The only way I can see the bottom of the application is to go into full screen on 1366x768 resolution.

**Comment by jochenkirstaetter** [comment]
Could provide a patch / PR for that issue. Currently, there is a pending one...

**Comment by jochenkirstaetter** [comment]
PR created: https://github.com/TryGhost/Ghost-Desktop/pull/295

**Comment by jochenkirstaetter** [comment]
Issue has been resolved in #295
