### ISSUE TITLE
Menu labels under "View" are out of sync

### ISSUE THREAD

**Issue by jochenkirstaetter** [TryGhost/Ghost-Desktop#289]
Hi,

The menu labels under "View" are out of sync with Ghost Admin.

- New Post ==> New story
- Content ==> Stories
- Navigation ==> Design

This might have an impact on the keyboard shortcuts (hotkeys), too. At least for Stories and Design.

Could provide a PR for that issue.

**Comment by felixrieseberg** [comment]
This was fixed in 1.4 🙌
