### ISSUE TITLE
Sidebar looks strange

### ISSUE THREAD

**Issue by fishcharlie** [TryGhost/Ghost-Desktop#291]
The sidebar for the Ghost Desktop on Mac looks super strange

<img width="997" alt="screen shot 2017-09-15 at 10 14 45 pm" src="https://user-images.githubusercontent.com/860375/30509046-563514ba-9a63-11e7-8af0-f58b3c6579ef.png">

**Comment by felixrieseberg** [comment]
Yeah, vibrancy seems to not be as awesome as hoped. This is now fixed, it'll be a configurable setting in 1.5.
