### ISSUE TITLE
`Alt` shortcuts overwrite special character input

### ISSUE THREAD

**Issue by whataflaw** [TryGhost/Ghost-Desktop#292]
When pressing the Alt + A, Alt + C and Alt + L keys while editing profile information I'm carried to the Apps, Code Injection and Labs tabs of the desktop app. These key combinations are necessary to produce Polish letters.

**Comment by felixrieseberg** [comment]
Oh boy, that's pretty terrible. We'll remap!

**Comment by whataflaw** [comment]
Pretty please, with sugar on top, do so. I am tearing my hair out
copy-pasting all my text from notepad ;)

2017-11-08 3:22 GMT+01:00 Felix Rieseberg <notifications@github.com>:

**Comment by jochenkirstaetter** [comment]
Hi @whataflaw 

That's already different in 1.4.0. The hotkeys are as following (Ctrl on Windows, replace with Cmd on Mac):
- Code injection: Ctrl+Alt+I
- Apps: Ctrl+Alt+A
- Labs: Ctrl+Alt+L

Does this still interfere with Polish special characters?

@felixrieseberg I think this issue might be resolved already since 1.4.0.

**Comment by whataflaw** [comment]
Well, I was using the 1.4.0 version. Right now I have switched from the
desktop app to the web app - unfortunately no luck here too. I would need
Alt + c, Alt + s and Alt + l to be freed. Otherwise I am still stuck with
"notepad".

2017-11-09 18:11 GMT+01:00 Jochen Kirstätter <notifications@github.com>:

**Comment by jochenkirstaetter** [comment]
If the problem exists in the "web app" than it's the repo here.
Please consider to move or create this issue in [Ghost Admin](https://github.com/TryGhost/Ghost-Admin) instead.

The hotkeys in Ghost Desktop are working as described and wasn't able to confirm your observations. I have to use Ctrl+Alt+<key> on Windows to jump around the app.

Sorry!

**Comment by whataflaw** [comment]
I reinstalled the desktop app, checked that the version is latest (1.4.0).
Confirmed my observations - both the desktop app and web app do not allow
me to type Polish special characters. Alt+a takes me to Apps, Alt+s
triggers spellchecker, Alt+l creates a list, Alt + c puts back-ticks
(code). All of these should turn out as ą, ś, ł, ć.

2017-11-10 7:50 GMT+01:00 Jochen Kirstätter <notifications@github.com>:

**Comment by kevinansfield** [comment]
This is an issue in the upstream editor dependency that's used in Ghost itself, there are open issues for it on that repo:

https://github.com/sparksuite/simplemde-markdown-editor/issues/616 and
https://github.com/sparksuite/simplemde-markdown-editor/issues/646

It's not something related to Ghost-Desktop.
