### ISSUE TITLE
Blog logo visibility issue

### ISSUE THREAD

**Issue by Leoooob** [TryGhost/Ghost-Desktop#293]
When the blog logo (favicon) has transparency, you can see the default icon underneath. 

This was discovered on OSx Sierra 10.12.6. Bug is pictured below:

![bug](https://gyazo.com/55423b431305a3d82b8e860d270d8997)

**Comment by jochenkirstaetter** [comment]
Same on Windows (Ghost Desktop v1.4.0)

**Comment by felixrieseberg** [comment]
This is now fixed (and will roll out in 1.5)!
