### ISSUE TITLE
Failed login with Ghost 1.9.0

### ISSUE THREAD

**Issue by kennethlimcp** [TryGhost/Ghost-Desktop#294]
Ghost-Desktop: 1.4.0
Ghost version: 1.9.0

<img width="1208" alt="screen shot 2017-09-27 at 19 42 32" src="https://user-images.githubusercontent.com/6760914/30911765-7419fb6e-a3bc-11e7-839a-15b37f4addfa.png">

**Comment by jochenkirstaetter** [comment]
Had to Refresh/Reload the Network page in Developer Tools to load the remote blog successfully. Be careful using Ctrl+R - you have to focus the right window first.

**Comment by vurtomatic** [comment]
@jochenkirstaetter thanks for the tip, just tried 1.40 with 1.16.1 and still getting a spinning circle.

**Comment by felixrieseberg** [comment]
This should be fixed now - this logic was pretty terrible in 1.4, but should be a lot better in 1.5.
