### ISSUE TITLE
Missing deb download for 1.4.0

### ISSUE THREAD

**Issue by popey** [TryGhost/Ghost-Desktop#296]
Visited https://ghost.org/downloads/ where I see:-

![image](https://user-images.githubusercontent.com/1841272/31941796-04300a5a-b8bb-11e7-975b-fa1eb96560cf.png)

However clicking the link gets me 1.3.0, not 1.4.0 listed in the image. I also note there's no deb in the releases https://github.com/TryGhost/Ghost-Desktop/releases/tag/v1.4.0

Can we get a deb for 1.4.0 please?

**Comment by felixrieseberg** [comment]
We added a download for 1.5, so I'm closing this. Sorry about 1.4!
