### ISSUE TITLE
Desktop App 1.4 can't log in to blog

### ISSUE THREAD

**Issue by vurtomatic** [TryGhost/Ghost-Desktop#297]
1.3 worked fine. 

1.4: No error, just a spinning circle.

Let me know if there's a way to provide a log.

Blog details:
```
Version 1.16.1
Environment production
Database sqlite3
Mail Direct

```

**Comment by jochenkirstaetter** [comment]
Duplicate of #294

**Comment by felixrieseberg** [comment]
We now have 1.5 out, so I'm closing this.
