### ISSUE TITLE
Ghost-Desktop unable to find my blog

### ISSUE THREAD

**Issue by intralizee** [TryGhost/Ghost-Desktop#308]
OS: macOS 10.13.2
Ghost Desktop Version: 1.5.0
Ghost Blog Version: 1.18.0

[07:53:24.914] gh-edit-blog: Validating Ghost url https://blog.alizée.com/ghost/
/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-log/renderer.js:34 [07:53:26.244] gh-edit-blog: Validation result: false
DevTools failed to parse SourceMap: file:///Applications/Ghost.app/Contents/Resources/app/ember/assets/vendor.map
DevTools failed to parse SourceMap: file:///Applications/Ghost.app/Contents/Resources/app/ember/assets/ghost-desktop.map
/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-log/renderer.js:34 [07:55:37.687] gh-edit-blog: Validating Ghost url https://blog.intralizee.com/ghost/
/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-log/renderer.js:34 [07:55:38.276] gh-edit-blog: Validation result: false
[07:57:39.958] gh-edit-blog: Validating Ghost url https://blog.intralizee.com/ghost/
/Applications/Ghost.app/Contents/Resources/app/node_modules/electron-log/renderer.js:34 [07:57:40.516] gh-edit-blog: Validation result: false

**Comment by felixrieseberg** [comment]
Thank you so much for reporting! That's a real bug, but luckily, I managed to fix it (https://github.com/TryGhost/Ghost-Desktop/pull/309).

I'll make a patch release this week that should allow you to use Ghost Desktop. Sorry for the trouble!
