### ISSUE TITLE
Duplicated keyboard shortcut in ubuntu version?

### ISSUE THREAD

**Issue by sten626** [TryGhost/Ghost-Desktop#311]
I recently starting using Ghost Desktop, and noticed the side-by-side preview keyboard shortcut is ctrl+alt+p. When I hit ctrl+alt+p it both opens the side-by-side preview AND publishes my post. This is not ideal. Please let me know if this is just me being an idiot.

**Comment by kevinansfield** [comment]
Closing as a duplicate of https://github.com/TryGhost/Ghost/issues/9296 (this is an issue in Ghost-Admin rather than the desktop client)

**Comment by felixrieseberg** [comment]
Closing because dupe.
