### ISSUE TITLE
When adding an element to a list, below list elements get replaced by NaNundefined

### ISSUE THREAD

**Issue by ryanhinojosa** [TryGhost/Ghost-Desktop#312]
### Issue Summary
When adding an element to a list, any list elements that are below will get replaced by NaNundefined. This is happening on desktop and the web editor.

Mac OS X - High Sierra - 10.13.2
Ghost 1.5.1

### Steps to Reproduce
1. Create 2 or more list elements
2. Add a new list element in the middle

![listerror](https://user-images.githubusercontent.com/14813548/34697745-572db446-f489-11e7-8853-cb9235462906.gif)

**Comment by kirrg001** [comment]
Hey @ryanhinojosa

This was already [reported](https://github.com/TryGhost/Ghost/issues/9372) and fixed. Will be released today.
