### ISSUE TITLE
does not seem to meet new unsplash api guidelines

### ISSUE THREAD

**Issue by boneskull** [TryGhost/Ghost-Desktop#316]
See [this post](https://medium.com/unsplash/unsplash-api-guidelines-28e0216e6daa) for more info.

It sounds like April 16 is the last day the Unsplash integration will work properly.

**Comment by kevinansfield** [comment]
Hey @boneskull 👋 Ghost is in compliance with Unsplash’s API guidelines and we’ve worked with Unsplash to ensure everything is implemented correctly, the integration is not going to stop working
