### ISSUE TITLE
[Quick fix] Dead image on README.md

### ISSUE THREAD

**Issue by dmxt** [TryGhost/Ghost-Desktop#317]
### Current state
Main readme.md of this repository
![g4rpnhu 1](https://user-images.githubusercontent.com/3248782/39058803-d55a13cc-448a-11e8-8910-e7b7522dca33.png)
Link: https://github.com/TryGhost/Ghost-Desktop/tree/master/docs#current-status

### Specifications:
```
Windows 8 64-bit
1. Cent Browser Version 3.2.4.23 (Official Build) (32-bit) (Chromium 64.0.3282.140)
2. Firefox Quantum 59.0.2 (64-bit)
```

### Debugs

[\[502\] Bad image in FF GET Headers response](https://i.imgur.com/4b0LsN4.png)
[\[200\] FF GET Headers response on working image](https://i.imgur.com/DVvjOZC.png)

**Comment by felixrieseberg** [comment]
Seems like we got that fixed. Thank you!
