### ISSUE TITLE
Desktop 1.6 on Win 10 thinks it's an Xbox game?!

### ISSUE THREAD

**Issue by talkingnews** [TryGhost/Ghost-Desktop#322]
I don't know if I've just got a weird install, but every time I start Ghost Desktop, it gives me some popups about recording my game, or sometimes it says "Press Windows + G to start", which then offers me to open GameBar.  🤔

**Comment by felixrieseberg** [comment]
😆 Oh Windows... it's possible that you once, by accident, hit the secret Windows Game shortcut (Win + (Alt) + G). I'm not entirely sure how you turn that off once it happened...

https://support.xbox.com/en-US/xbox-on-windows/social/record-game-clips-game-dvr-windows-10. I did find this though: https://support.steampowered.com/kb_article.php?ref=6239-DZCB-8600

Either way, I'm afraid that this isn't something we can control from within Ghost, so I'll have to close this. Sorry!
