### ISSUE TITLE
Koenig embed card support

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-Desktop#326]
Ghost 2.0's soon-to-be-launched editor ([Koenig](
https://forum.ghost.org/t/koenig-editor-beta-release/1284)) has full support for embeds within the editor. Embed cards will pull content from an external service which will usually include scripts or iframes to display things like tweets or videos.

Ghost-Desktop loads+displays embeds fine but shortly afterwards they turn into white blocks where the content was once visible.

**Comment by felixrieseberg** [comment]
Huh, fascinating. First debug step should be to update Electron to v3, I'm hoping that a later Chrome version will fix this for us.

**Comment by kevinansfield** [comment]
Testing a naive Electron upgrade (`npm i electron@beta`, `npm start`) the embed cards no longer get switched to white boxes so I think there's hope! 😄

**Comment by kevinansfield** [comment]
Closing as we're on electron v3 and the issue no longer exists.
