### ISSUE TITLE
Random Colors for Ghost Buttons

### ISSUE THREAD

**Issue by felixrieseberg** [TryGhost/Ghost-Desktop#57]
The buttons for individual blogs in the quick switch area currently have all the same color - to make them more obviously distinguishable, they should have a random background color (ideally, a pleasant one). Numerous libraries exist that randomly generate nice colors.

**Comment by bnookala** [comment]
Should we regenerate these on app start? Or consider making it a property on the model, so the colors 'stick'?

**Comment by felixrieseberg** [comment]
They should probably be on the model and have a default value. Also, it'd be cool if the model had a little method "randomColor" that generates a new color. Pseudocode:

```
color: DS.attr('string', {
    defaultValue() { return niceColor(); }
})

randomColor() {
  this.set('color', niceColor());
}
```
