### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by felixrieseberg** [TryGhost/Ghost-Desktop#6]
The app should update itself whenever a new version is available, using GitHub releases as the basis. This is a little bit more tricky than it might seem and should involve the following:

 * [x] Code Signing OS X
 * [x] Code Signing Windows
 * [x] Squirrel.Mac integration
 * [x] Squirrel.Windows integration, using electron-winstaller
 * [x] Fallback information

The fallback information should be a simple "Hey, there's a new version available - click here to download" information in the app, should we fail auto-updating. This will also be required to update the Linux version, given that auto-updating apps there is so messy that we'd rather not mess with people's systems.

@JohnONolan: Code signing is required so that we don't see ugly "THIS APP IS SUPER DANGEROUS FOR REALZ" messages on OS X and Windows. A fresh MacBook will even flat-out refuse to launch the app. Bonus points: It's required for the Mac App Store. We should probably knock this out later in the process while sitting next to each other.

**Comment by JohnONolan** [comment]
Yup, completely agree with all of these points!
