### ISSUE TITLE
Error loading DLL on Windows 10 64x

### ISSUE THREAD

**Issue by Mooash** [TryGhost/Ghost-Desktop#63]
After adding a blog on a  Windows 10 64x machine the following errors get printed into the debugging console

```
Unhandled promise rejection Error: A dynamic link library (DLL) initialization routine failed.(…)
    (anonymous function) @ vendor.js:2756
```

```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\James\AppData\Local\ghost\app-0.1.0\resources\app\node_modules\keytar\build\Release\keytar.node
    module.(anonymous function) @ ATOM_SHELL_ASAR.js:140
    Module._extensions..node @ module.js:450module.(anonymous function) @ ATOM_SHELL_ASAR.js:140
    Module.load @ module.js:356
    Module._load @ module.js:313
    Module.require @ module.js:366
    require @ module.js:385
    (anonymous function) @ C:\Users\James\AppData\Local\ghost\app-0.1.0\resources\app\node_modules\keytar\lib\keytar.js:4
    (anonymous function) @ C:\Users\James\AppData\Local\ghost\app-0.1.0\resources\app\node_modules\keytar\lib\keytar.js:58
    Module._compile @ module.js:425
    Module._extensions..js @ module.js:432
    Module.load @ module.js:356
    Module._load @ module.js:313
    Module.require @ module.js:366
    require @ module.js:385
    getPassword @ ghost-desktop.js:915
    signin @ ghost-desktop.js:330
    _handleLoaded @ ghost-desktop.js:359
    (anonymous function) @ ghost-desktop.js:317
    jQuery.event.dispatch @ vendor.js:9372
    elemData.handle @ vendor.js:9184
    WebViewImpl.dispatchEvent @ C:\Users\James\AppData\Local\ghost\app-0.1.0\resources\atom.asar\renderer\lib\web-view\web-view.js:142
    dispatchEvent @ C:\Users\James\AppData\Local\ghost\app-0.1.0\resources\atom.asar\renderer\lib\web-view\guest-view-i…:53
    (anonymous function) @ C:\Users\James\AppData\Local\ghost\app-0.1.0\resources\atom.asar\renderer\lib\web-view\guest-view-i…:64
    emitTwo @ events.js:87
    emit @ events.js:172
```

The "loading" gif/circle never disappears and you never get presented with your blog to manage.

I've repeated this several times and tried removing everything in AppData and reinstalling without luck. I'm on windows 10 Pro.

**Comment by CaiJimmy** [comment]
Same here  
![image](https://cloud.githubusercontent.com/assets/5889006/13947334/36077fba-f01a-11e5-8c4b-8f2c9e5a77c5.png)

Windows 10 Pro 64-bit

**Comment by parzzix** [comment]
I can report the same issue also.

**Comment by felixrieseberg** [comment]
Thank you all! I identified an issue with the DLL compilation (we're storing your passwords in the native Windows secure key vault, which is failing here), which lead me to fix an issue in one of our build tools (ember electron).

I'll push out a new version in about two hours, probably sooner. Again, thanks a lot!

**Comment by felixrieseberg** [comment]
Hey everyone, I pushed a version that works well on my 32 and 64 machines, but I'd love to hear that it also works for y'all. I'd really appreciate it if you could give it a try! Also, thanks again for helping me work out these bugs.

https://github.com/TryGhost/Ghost-Desktop/releases/tag/0.1.1

**Comment by Mooash** [comment]
This works fine on Windows 10 64x now.

**Comment by kaiserhase** [comment]
Awe yiss! That fixed my issue lickity-split. Thanks @felixrieseberg

**Comment by felixrieseberg** [comment]
Good to hear, thanks a lot! Closing this for now.
