### ISSUE TITLE
Mixed content images: Can't load images via http over secure site

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost-Desktop#66]
As a ghost pro customer, my backend lives on `ghost.io`, served over HTTPS, but my frontend is served over http. Fittingly, any images I upload to my blog are then served over http

Right now, the app is blocking these images for security reasons:

```
Mixed Content: The page at 'https://novaugust.ghost.io/ghost/699/' was loaded over HTTPS, but requested an insecure image 'http://blog.novaugust.net/content/images/2015/10/output_QuBpPn.gif'.
This request has been blocked; the content must be served over HTTPS.
```

**Comment by bnookala** [comment]
@felixrieseberg I thought this could be fixed in `main/entry.js` by adding the allowDisplayingInsecureContent key to the browser window instantiation, but it doesn't appear to work for me; I'm still getting mixed content errors. Any ideas?

```
    mainWindow = new BrowserWindow({
        width: mainWindowState.width,
        height: mainWindowState.height,
        x: mainWindowState.x,
        y: mainWindowState.y,
        allowDisplayingInsecureContent: true,
        show: false
    });
```

**Comment by bnookala** [comment]
Found the problem. BrowserWindow doesn't pass on its options to the webview tag. Looks like there's an issue open to fix it, but not much activity around it: https://github.com/atom/electron/issues/2749

**Comment by felixrieseberg** [comment]
Thanks for the research! In the meantime, we can add the `disablewebsecurity` to the webview tag, which should achieve the same thing.

**Comment by felixrieseberg** [comment]
Since you already did all the work, want to PR? I'd feel dirty for taking it. It's a one-line change ;-)

**Comment by bnookala** [comment]
@felixrieseberg sure :+1:

**Comment by felixrieseberg** [comment]
Thanks Matt, Thanks Bhargav :+1: 

(Also, Matt: You're gonna be at EmberConf, right?)

**Comment by novaugust** [comment]
@felixrieseberg Me and a bottle of fine whiskey are looking forward to seeing you again :D
