### ISSUE TITLE
Watchman overload

### ISSUE THREAD

**Issue by qLb** [TryGhost/Ghost-Desktop#67]
### I encountered this on npm start

A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1458753005: inotify-add-watch(/home/qlb/projects/metaljack/ghost/core/client/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/source-map-support/node_modules/source-map/test/source-map) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1458753005: inotify-add-watch(/home/qlb/projects/metaljack/ghost/core/client/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/source-map-support/node_modules/source-map/test/source-map) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch
```
    at ChildProcess.<anonymous> (/home/qlb/GhostApp/Ghost-Desktop-0.1.1/node_modules/fb-watchman/index.js:206:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:479:12)
```

not a bug but can be an issue 
### First things first, my architecture:
`Linux 4.4.3-1-ARCH #1 SMP PREEMPT Fri Feb 26 15:09:29 CET 2016 x86_64 GNU/Linux`
### Fix that works for me:
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by felixrieseberg** [comment]
This is now fixed.
