### ISSUE TITLE
Available for self-installed setup AND Ghost Pro users ?

### ISSUE THREAD

**Issue by pascalandy** [TryGhost/Ghost-Desktop#68]
I assume this is available for all Ghost installations types (Sefl-installed and GhostPro), but I'd like to double check what is the minding here :) 

Will the ghost desktop application available for self-installed setup AND Ghost Pro users?

From there, would an iOS version app follow ?

Cheers!

**Comment by bnookala** [comment]
Can't speak for an iOS version, but yes, Desktop should work for both GhostPro and self-installed, so long as you set it up to point to the /ghost endpoint.

**Comment by pascalandy** [comment]
Should work is not a definitive `run Hell Yeah!` right?

**Comment by bnookala** [comment]
@pascalandy there's nothing about the code that will reject self-hosted instances in preference for GhostPro, so that's a definitive 'hell yeah, it'll work for both'.

**Comment by felixrieseberg** [comment]
:+1:

**Comment by pascalandy** [comment]
Now you're talking @bnookala :)

> there's nothing about the code that will reject self-hosted instances in preference for GhostPro, so that's a definitive 'hell yeah, it'll work for both'. :dancers:
