### ISSUE TITLE
Adding post image on Win 64

### ISSUE THREAD

**Issue by primaltutor** [TryGhost/Ghost-Desktop#72]
I wrote a new post and tried to add a post image under post settings. All I get is the little cat sitting there bobbing his head. It doesn't seem to upload. I had to log into website to add the image. I am using 64b Windows 10

**Comment by mece888** [comment]
Same problem here, but on OSX. Can't upload post image in the Ghost App (works on the web).

**Comment by felixrieseberg** [comment]
Thanks for the info - merging this with #73.
