### ISSUE TITLE
Build for Linux

### ISSUE THREAD

**Issue by varod** [TryGhost/Ghost-Desktop#74]
It is not an issue but a request. If we can have a linux-x64 build as windows OSX :)

I've succeed in building it more or less  easily but a direct access should be great :)

Here is a small blog post (in french) on what i've done : https://blog.valvin.fr/2016/03/25/installer-ghost-desktop-sur-ubuntu/

**Comment by felixrieseberg** [comment]
Yes, the public build will definitely be made available for Linux!

**Comment by felixrieseberg** [comment]
Paging @halfdan: Any chance you could try grabbing the repo and making a build? We probably have to do some work around the auto-updater (and ensure it doesn't run), but I'd love to see if everything else works fine.

**Comment by halfdan** [comment]
Absolutely - I'm currently OOO though. Will be back on Saturday and check
it out!

**Comment by THPubs** [comment]
+1 For this!

**Comment by drachenzauberei** [comment]
Looking forward to a working Linux build! :)

**Comment by envygeeks** [comment]
Looks like this is done, we just installed this onto several of our Desktops, thanks!

**Comment by felixrieseberg** [comment]
It is! Thanks for installing :)
