### ISSUE TITLE
Drag-and-drop image into Post Settings fails

### ISSUE THREAD

**Issue by scottw** [TryGhost/Ghost-Desktop#79]
(OS X 10.11.4, Ghost build 0.36.2) If I drag and drop an image into the "Add post image" area of Post Settings, the image fills the Ghost pane (hiding or replacing the editor) and I don't know how to navigate from here. I close Ghost and re-open it to try again. If I click the "Add post image" area and us its file picker it works fine.

Further, if I try to look at the developer tools, I get an uncaught exception:

<img width="532" alt="screen shot 2016-03-27 at 9 52 52 pm" src="https://cloud.githubusercontent.com/assets/849487/14070674/c5a8ffea-f466-11e5-8bae-1842ff65f6e7.png">

**Comment by felixrieseberg** [comment]
Thanks a lot - we need to appropriately handle the "drag and drop" event on the Ghost app, ensuring that the event is actually handed down to the Ghost instance. Thanks!

**Comment by felixrieseberg** [comment]
@bnookala's if he wants it :+1:
