### ISSUE TITLE
HTML Codes in Title Bar

### ISSUE THREAD

**Issue by IdiotBox** [TryGhost/Ghost-Desktop#85]
One of my Blog's is "Lop's Thoughts." but in the App Title Bar it shows `Ghost - Lop&#x27;s Thoughts.`

I'm running Windows 10 x64 with Developer Preview 2.
![ghost-desktop-bug](https://cloud.githubusercontent.com/assets/752145/14143022/dc79b52c-f680-11e5-89e3-d165135d4306.png)

**Comment by bnookala** [comment]
Ah yeah… looks like the raw string being passed here contains HTML entities, which we're not decoding. I've got a PR open to fix this :)

Thanks for reporting!
