### ISSUE TITLE
Special chars in window titel

### ISSUE THREAD

**Issue by Sheogorath-SI** [TryGhost/Ghost-Desktop#90]
If you use special chars in blog names like `Sheogorath's Blog` the `'` is placed as `&#x27;` in the title.

I guess this also happens by other special chars.

**Comment by bnookala** [comment]
I don't think we've rolled the fix into the built version of Ghost-Desktop, but #86 should fix this, and has been merged into master.

Thanks!

**Comment by felixrieseberg** [comment]
Yep, fixed in #86. Closing.
