### ISSUE TITLE
Refresh Contributors every Week

### ISSUE THREAD

**Issue by felixrieseberg** [TryGhost/Ghost-Desktop#95]
Currently, we download the list of contributors for the credits once (and then never again). That should change, the [logic here](https://github.com/TryGhost/Ghost-Desktop/blob/master/app/components/gh-preferences.js#L13) should also save *when* the contributors list was downloaded - and fetch it again, if it's too old.

**Comment by JohnONolan** [comment]
Would it be easier to ship this (like Ghost core) as a static list, when built?

**Comment by bnookala** [comment]
Think I agree with John here. We can just keep that list of contributors saved into a JSON file that's rebuilt on major/minor version changes.

**Comment by felixrieseberg** [comment]
Seems sensible to me.

**Comment by bnookala** [comment]
I have an *almost* working version of this. Just trying to work out some broken tests.

**Comment by jaswilli** [comment]
If you're not already, it's probably worthwhile to use the exact same process as used in the main Ghost project for this. We have an npm package to pull the contrib metadata as part of the build process.
