### ISSUE TITLE
Move Prefs

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost-Desktop#96]
It'd be great to see the preferences screen follow the convention of existing under the main toolbar "Ghost" as "Preferences" - also triggered with `CMD+,`

I don't think we need the settings icon in the sidebar UI here :)

![image](https://cloud.githubusercontent.com/assets/120485/14331057/78f58b5c-fbf8-11e5-8a22-8d5db37f6923.png)

**Comment by bnookala** [comment]
@felixrieseberg I'll go ahead and do this, if you haven't already.

**Comment by felixrieseberg** [comment]
:+1:
