### ISSUE TITLE
npm run build-native-debs fails on OS X

### ISSUE THREAD

**Issue by alecho** [TryGhost/Ghost-Desktop#97]
```
$ npm run build-native-deps
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/andrewlechowicz/.nvm/versions/node/v5.10.1/bin/node" "/Users/andrewlechowicz/.nvm/versions/node/v5.10.1/bin/npm" "run" "build-native-deps"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! missing script: build-native-deps
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /projects/Ghost-Desktop/npm-debug.log
```

OS X 10.11.4

**Comment by felixrieseberg** [comment]
I'm sorry, it's actually `build-native-deps-32` or `build-native-deps-64`. I'll update the docs!

**Comment by felixrieseberg** [comment]
Updated!

**Comment by alecho** [comment]
Thanks. I'm now getting a `sh: electron-rebuild: command not found` with the updated command. I can paste the full npm output if needed.

**Comment by felixrieseberg** [comment]
Did you run `npm install`? The command should be in `./node_modules/.bin/electron-rebuild` (or, on Windows, `.\node_modules\.bin\electron-rebuild.cmd`).

**Comment by alecho** [comment]
I did. I also did a `git fetch` before that and pull in 5 commits. I'm ran nombom for sanity and that seemed to fix it. Must have been a cache issue or similar.
